---
  - name: Install Docker for raspberrypi
    shell: curl -sSL https://get.docker.com | sh
  
  - name: increase virtual memory
    command: sysctl -w vm.max_map_count=262144

  - name: download and launch a docker elk container
    docker_container:
      name: elk
      image: sebp/elk
      state: started
      published_ports:
        - 5601:5601
        - 9200:9200
        - 5044:5044
