---
  - name: Download Grafana package
    get_url: 'https://dl.grafana.com/oss/release/grafana_6.6.1_armhf.deb'

  - name: Install Required Packages
    apt:
    update_cache: yes
    deb: ./grafana_6.6.1_armhf.deb