---   
- name: Install needed packages
  apt:
    update_cache: yes
    install_recommends: yes
    pkg:
      - git
      - vim
      - docker.io
      - python3-pip

- name: install python docker module
  pip:
    name: docker

- name: Install docker with raspberry pi specific script
  shell: curl -sSL https://get.docker.com | sh