---
- name: Change Hostname to 'dvwa'
  hostname:
    name: dvwa

- name: Copy hosts file into place
  copy:
    src: hosts
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644

# - name: 
#   apt_repository:
#     repo: http://ftp.de.debian.org/debian
#     state: present

- name: Install needed packages
  apt:
    update_cache: yes
    install_recommends: yes
    pkg:
      - apache2
      - php
      - mariadb-server
      - php-mysql
      - php-gd

- name: copy php.ini into place
  copy:
    src: php.ini
    dest: /etc/php5/apache2/php.ini
    owner: root
    group: root
    mode: 0644
  
- name: copy config.inc.php.dist into place
  copy:
    src: config.inc.php.dist
    dest: /var/www/html/dvwa/config/config.inc.php.dist
    owner: root
    group: root
    mode: 0755

- name: Restart
  reboot: