---
  - name: Install influx key
    shell: wget -qO- https://repos.influxdata.com/influxdb.key | apt-key add -
    args:
      warn: no

  - name: Add influx repo to sources
    apt_repository: 
        repo: 'deb https://repos.influxdata.com/debian buster stable'
        state: present
  
  - name: Download Grafana package
    get_url: 
      url: 'https://dl.grafana.com/oss/release/grafana_6.6.1_armhf.deb'
      dest: /home/pi
 
  - name: Install Grafana package
    apt:  
      deb: /home/pi/grafana_6.6.1_armhf.deb    
  
  - name: Install Required Linux Packages
    apt:
      update_cache: yes
      pkg:
      - python-pip
      - python3-pip
      - python3-influxdb
      - speedtest-cli
      - influxdb
      - vim
      - tmux
      - fail2ban
      - ufw

  - name: Install Required Python Packages
    pip:
      name: 
      - requests
      - influxdb
  
  
 