---
  - name: Enable InfluxDB
    systemd: 
      name: influxdb
      enabled: yes
      masked: no
      state: started

  - name: Create Influx Database
    influxdb_database:
      hostname: "raspberrypi.local"
      database_name: "internetspeed"
      username: "speedmonitor"
      password: "pimylifeup"

  # - name: Configure Influx Database
  #   shell: |
  #     influx
  #     CREATE DATABASE internetspeed
  #     CREATE USER "speedmonitor" WITH PASSWORD 'pimylifeup'
  #     GRANT ALL ON "internetspeed" to "speedmonitor"
  #     quit