---
  - name: Copy over Grafana.ini provisioning file
    copy:
      src: grafana.ini
      dest: /etc/grafana/grafana.ini
      owner: root
      group: root
      mode: 0540

  - name: Enable Grafana
    systemd: 
      name: grafana-server
      enabled: yes
      state: started

