---
  - name: Create Directory for storing Speed Tests
    file:
      path: /home/pi/speedtest
      state: directory
      owner: pi
      group: pi
      mode: '0755'
  
  - name: Copy python speed-test script into place
    copy:
      src: speedtest.py
      dest: /home/pi/speedtest.py
      owner: pi 
      group: pi
      mode: '0755'

  - name: Run script a few times to verify it's working and populate some data
    shell: for i in {1..3}; do python3 /home/pi/speedtest.py; done

  - name: Set the script to run every 30 mins
    cron:
      name: "check speed"
      minute: "0,30"
      job: "python3 /home/pi/speedtest.py"